### ISSUE TITLE
tcp,::1,portnum only listens on IPv6

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/gensio#36]
Hi,

In Debian, I would like to have ser2net listen on localhost only in the default configuration. Most services, when configured to listen on "::1", the IPv6 localhost address, will also accept connections to 127.0.0.1. ser2net doesn't.

I think this can be set by some TCP socket option. Sorry that I cannot be of more help here, I am not a programmer.

Please consider adding this option so that listening to ::1 will also allow IPv4 to be used.

Greetings
Marc

**Comment by Zugschlus** [comment]
The socket option in question is IPV6CTL_V6ONLY, so the appropriate call would probably be setsockopt(sd, IPPROTO_IPV6, IPV6_V6ONLY, ...

**Comment by cminyard** [comment]
On Sat, Nov 27, 2021 at 12:26:36AM -0800, Zugschlus wrote:
> Hi,
> 
> In Debian, I would like to have ser2net listen on localhost only in the default configuration. Most services, when configured to listen on "::1", the IPv6 localhost address, will also accept connections to 127.0.0.1. ser2net doesn't.
> 
> I think this can be set by some TCP socket option. Sorry that I cannot be of more help here, I am not a programmer.
> 
> Please consider adding this option so that listening to ::1 will also allow IPv4 to be used.

Well, it doesn't exactly work this way.  You can enable this flag with a
::1, but it's not going to be accessible from IPv4 because it's not an
address IPv4 can get to.  It took me a long time to figure out how all
this works.

You can say "tcp,localhost,2134" and it will work like you want (unless
your distro is screwed up, which does happen).  It works because
getaddrinfo returns two addresses for localhost:

  $ tools/gensiot -a -p tcp,localhost,1234
  Address 0(0): ipv6,::1,1234
  Address 1(0): ipv4,127.0.0.1,1234

and gensio will open both of them and listen.  If you put nothing, like
"tcp,2134", it will set the IPV6_V6ONLY flag on an INADDR_ANY address,
which does work.  If you want an IPV6-only INADDR_ANY address, you do
"tcp,ipv6,1234".

The way to get a single address that works on both IPv4 and IPv6, you
have to use either INADDR_ANY or an IPv6 mapped address, which is an
IPv6 address that starts with ::ffff:.  The way gensio represents this is
with ipv6n4.  For instance:

  $ tools/gensiot -a -p tcp,ipv6n4,localhost,1234
  Address 0(0): ipv6,::ffff:127.0.0.1,1234

Then you can connect via IPv4 with 127.0.0.1 or with ::ffff:127.0.0.1
via IPv6.  If you want to hand-specify all addresses, you can do that
by just listing all the addresses:

  $ tools/gensiot -a -p tcp,127.0.0.1,1234,::1,1234
  Address 0(0): ipv6,::1,1234
  Address 1(0): ipv4,127.0.0.1,1234

I'm not sure there is any program where ::1 will get you an IPv4
accessible address.  getaddrinfo() will not return one, even with
AI_V4MAPPED set, and IPV6_V6ONLY set to false will not make any
difference.

-corey

**Comment by Zugschlus** [comment]
Thanks for explaining. After digging around on my systems, I can confirm that. Most other software does it the same way. It didn't occur to me that localhost does do what I want. Closing the issue.

Maybe gensio.5 can include a hint for that?

**Comment by cminyard** [comment]
On Sun, Nov 28, 2021 at 12:06:00PM -0800, Zugschlus wrote:
> Thanks for explaining. After digging around on my systems, I can confirm that. Most other software does it the same way. It didn't occur to me that localhost does do what I want. Closing the issue.

Yeah, it's not completely intuative.  Like I said, it took me quite a
while to figure all this out, and the man pages didn't help a lot.

> 
> Maybe gensio.5 can include a hint for that?

There is a section named "IPv6, IPv4, and host names", I'll try to make
it more clear what is going on.

-corey

**Comment by cminyard** [comment]
On Sun, Nov 28, 2021 at 12:06:00PM -0800, Zugschlus wrote:
> Thanks for explaining. After digging around on my systems, I can confirm that. Most other software does it the same way. It didn't occur to me that localhost does do what I want. Closing the issue.
> 
> Maybe gensio.5 can include a hint for that?

Ok, I"ve added some of the explaination to that man page.

-corey
