### ISSUE TITLE
Session end on failing TIOCCBRK

### ISSUE THREAD

**Issue by Bastian-Krause** [cminyard/gensio#39]
I am using a setup where I start a generic ser2net for each serial port.

A rather long time ago a failing `TIOCCBRK` would not end the session:
https://github.com/cminyard/gensio/blob/08285ec9a51183a8c4e32f6fb3da77abab3814ee/ChangeLog#L398-L400

This seems to be different now:

https://github.com/cminyard/gensio/blob/3f6c3ce988a7a090748d84aab8beaf7381aa517b/lib/gensio_osops.c#L1963-L1973

..leading to:
```
openat(AT_FDCWD, "/dev/ttyACM0", O_RDWR|O_NOCTTY|O_NONBLOCK) = 9
ioctl(9, TCGETS2, {B9600 opost isig icanon echo ...}) = 0
ioctl(9, TCSETS2, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(9, TIOCCBRK)                      = -1 EPIPE (Broken pipe)
ioctl(9, TCSETS2, {B9600 opost isig icanon echo ...}) = 0
close(9)                                = 0
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\377\373\3\377\375\3\377\373\1\377\376\1\377\375\0\377\373\0\377\375,", iov_len=21}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 21
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="Device open failure: Remote end "..., iov_len=51}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 51
```

Should a failing `TIOCCBRK` really be fatal?

**Comment by cminyard** [comment]
On Tue, Apr 05, 2022 at 06:02:19AM -0700, Bastian Krause wrote:
>  I am using a setup where I start a generic ser2net for each serial port.
> 
> A rather long time ago a failing `TIOCCBRK` would not end the session:
> https://github.com/cminyard/gensio/blob/08285ec9a51183a8c4e32f6fb3da77abab3814ee/ChangeLog#L398-L400
> 
> This seems to be different now:
> 
> https://github.com/cminyard/gensio/blob/3f6c3ce988a7a090748d84aab8beaf7381aa517b/lib/gensio_osops.c#L1963-L1973
> 
> ..leading to:
> ```
> openat(AT_FDCWD, "/dev/ttyACM0", O_RDWR|O_NOCTTY|O_NONBLOCK) = 9
> ioctl(9, TCGETS2, {B9600 opost isig icanon echo ...}) = 0
> ioctl(9, TCSETS2, {B115200 -opost -isig -icanon -echo ...}) = 0
> ioctl(9, TIOCCBRK)                      = -1 EPIPE (Broken pipe)
> ioctl(9, TCSETS2, {B9600 opost isig icanon echo ...}) = 0
> close(9)                                = 0
> sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\377\373\3\377\375\3\377\373\1\377\376\1\377\375\0\377\373\0\377\375,", iov_len=21}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 21
> sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="Device open failure: Remote end "..., iov_len=51}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 51
> ```
> 
> Should a failing `TIOCCBRK` really be fatal?

That's a difficult question.  If this happens, it means your device
doesn't support this and returns an error.  And EPIPE is a strange one
to return, but, whatever.

The right thing for you to do, no matter what happens, is add nobreak to
the serial port options.  That prevents it from turning off break at
startup.  I could make it not fail, but it would still generate a log.

Since you can turn this off, I am inclined to leave it like it is.  A
break is a pretty standard serial port thing.  If you can't turn it
off at startup, that would be an important thing to know if you were
using this.  But I'm not 100% sure.

-corey

**Comment by jluebbe** [comment]
This issue came up in [labgrid](https://github.com/labgrid-project/labgrid/), where we use ser2net to provide network access to USB serial devices. We use udev to detect them as they are connected and then start a ser2net process for each. At that level, we don't know whether a given device supports sending breaks and it seems that the USB protocol doesn't make this discoverable (the device just responds with an error if it doesn't support the request).

As far as I can see, the TIOCCBRK call on startup is only to make sure that we're not sending break already. So if that TIOCCBRK fails, we could infer that the device most likely doesn't support break and thus is not already sending break. In that case, we could continue as normal, as the device is already in the intended state.

Later if an RFC2217 client then requests to send break, an error reply could be sent. I think that was the behavior before the refactoring into gensio.

**Comment by cminyard** [comment]
My mail here got lost, but yes, I was wrong to break this, and it's fixed in 2.3 and 2.4.  Next release will have it.

Thanks,

-corey

**Comment by jluebbe** [comment]
Thanks for the quick fix! We'll try with our problematic device.

**Comment by cminyard** [comment]
On Thu, Apr 07, 2022 at 01:47:02AM -0700, Jan Lübbe wrote:
> This issue came up in [labgrid](https://github.com/labgrid-project/labgrid/), where we use ser2net to provide network access to USB serial devices. We use udev to detect them as they are connected and then start a ser2net process for each. At that level, we don't know whether a given device supports sending breaks and it seems that the USB protocol doesn't make this discoverable (the device just responds with an error if it doesn't support the request).
> 
> As far as I can see, the TIOCCBRK call on startup is only to make sure that we're not sending break already. So if that TIOCCBRK fails, we could infer that the device most likely doesn't support break and thus is not already sending break. In that case, we could continue as normal, as the device is already in the intended state.
> 
> Later if an RFC2217 client then requests to send break, an error reply could be sent. I think that was the behavior before the refactoring into gensio.

Yes, and I failed to capture the rationale in the original change.  I've
put in a change to correct this; it will be out in the next 2.3.x and
2.4.x releases.

Thanks for pointing this out.

-corey
