### ISSUE TITLE
Feature request: Send winch when receiving telnet IAC NAWS commands (RFC 1073)

### ISSUE THREAD

**Issue by volfyd** [cminyard/gensio#55]
Currently gensiot can send winch updates if you are connected pty<->stdio or similar. It would be great if when acting as a telnet server the window size updates could be propogated.

My use case is running the telnet protocol over a serial port, and allowing the client to be resized.

Really cool library by the way.

**Comment by cminyard** [comment]
Sorry for the delay on this, I'm not getting notifications of issues added.

I have pushed up something into the master branch that should implement this.  I don't have an easy way to try it out (beyond the internal tests I wrote), can you try it?

**Comment by cminyard** [comment]
I'm also wondering what you are using on the other end of the connection.  I've tested this with gensiot on both ends and it seems to work ok.

**Comment by volfyd** [comment]
Wow thank you! A quick test with

```
gensiot -i pty,bash -a 'telnet(winsize=true),tcp,3001'
```
and then
```
telnet localhost 3001
```
works great.

My use case is having a VM with no network access that I want to be able to log into over serial. It was painful to do without window resizing.

I still need to try and run the telnet protocol over serial. I will try to get the right gensiot commands going on my setup and I'll report back on how it goes.

**Comment by cminyard** [comment]
> 
> My use case is having a VM with no network access that I want to be able to log into over serial. It was painful to do without window resizing.

Ah, I had never thought of that.  But that's the thing, you never think of everything, that's why flexible tools are good.

> 
> I still need to try and run the telnet protocol over serial. I will try to get the right gensiot commands going on my setup and I'll report back on how it goes.

For gensiot, it's:

  gensiot -i "pty,bash -l" 'telnet(mode=server,winsize),serialdev,/dev/ttyttyS0,115200n81'

on the target side.  You can put this in /etc/inittab, or restart it with systemd when it ends. I assume you have a network connection on the VM, so you can use normal telnet for that, or:

  gensiot 'telnet(winsize),tcp,localhost,<port>'

There is a bit of an issue with this.  The server side there is hooked to a serial port, and it's going to negotiate immediately at startup, but not after that.  So when you connect later it's not going to re-negotiate.  It may not matter, not sure.

I do have a protocol that's part of gensio that is connection oriented that you can put between telnet and serialdev.  It will solve those problems, but you can't use normal telnet then.

**Comment by cminyard** [comment]
Actually, this is much harder than I thought at first.  The trouble is that telnet is designed to run over a connection oriented protocol.  When you start the server sitting on the serial port, it's going to immediately try to negotiate, and of course there's nothing on the other end.  When the client connects, it's going to negotiate, but the server is going to assume that the client has already received it's negotiation messages so it won't re-send them.  I'm not sure how that's going to work.

If you want to try this, you can do:

gensiot -i "pty,-login"  'telnet(mode=server,winsize),serialdev,/dev/ttyPipeA0,115200n81'

in place of the normal getty.  I'm using a serial port simulator, you obviously substitute the serial port you need.  This also has other odd behaviour because it doesn't know if the other end has connected to, or disconnected from, the serial port.  Doing an "exit" won't drop the connection, for instance, it will just give you a login prompt.  You would have to do the telnet (or gensiot) disconnect.

Note that you can substitute "bash -l" instead of "-login" if you want toq just run bash and not do a normal login.

If you try this running the server from a normal command line ^C will not work because of the way controlling terminals work.  It's kind of hard to explain, but it deals with the way SIGINT is handled.  But it should be fine running from init.

There is a way to work around the strangeness, but you will have to run gensiot on both sides.  There is a connection-oriented protocol that will run over a serial port (or any stream) named relpkt. (It has to run with msgdelim because it actually needs a packet protocol, and msgdelim converts from a stream to a packet protocol.) It will provide the connection-oriented thing you need for telnet to be happy.  To do this you would run:
```
  gensiot -i "pty,-login" 'telnet(mode=server,winsize),relpkt(mode=server),msgdelim,serialdev,/dev/ttyPipeA0,115200n81'
```
And to connect to the other end of a serial port you would use:
```
  gensiot 'telnet(winsize),relpkt,msgdelim,serialdev,/dev/ttyPipeB0,115200n81'
```
or if to a telnet port:
```
  gensiot 'telnet(winsize),relpkt,msgdelim,tcp,localhost,<port>'
```

If you want full-on encrypted and two-way authenticated logins, the README.rst describes how to do this in the conacc section using gtlsshd and gtlssh.  But I'm guessing you don't care about that.

**Comment by cminyard** [comment]
Any news on this?  I'm curious what solution you used.
